---
plugin: netbox
api_endpoint: http://192.168.137.100:8000
token: 0123456789abcdef0123456789abcdef01234567
validate_certs: False
config_context: True
group_by:
  - device_roles
compose:
  ansible_network_os: platform.slug
