---
# to execute: ansible-playbook playbook.yml -i hosts.yml -u <username> -K
- hosts: data_controller
  gather_facts: False
  become: yes
  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest
      register: yum_output

    - name: install epel-release for AWX
      yum:
        name: epel-release
        state: latest
      register: epel_release_output

    - name: install additional packages
      yum:
        name: '{{ item }}'
        state: latest
      loop:
        - git
        - gcc
        - gcc-c++
        - nodejs
        - gettext
        - device-mapper-persistent-data
        - lvm2
        - python3-pip
        - python-pip
        - vim
        - nmap-ncat
      register: others_output

    - name: set sysctl overcommit_memory to 1
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: '1'
        state: present
        reload: yes

    - name: set sysctl net.core.somaxconn to 65535 (for redis)
      ansible.posix.sysctl:
        name: net.core.somaxconn
        value: '65535'
        state: present
        reload: yes

    - name: set Transparent Huge Pages (THP) support to disabled (for redis)
      shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

    - name: set THP premanently in rc.local
      blockinfile:
        path: /etc/rc.local
        block: |
          if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
              echo never > /sys/kernel/mm/transparent_hugepage/enabled
          fi

    - name: add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: install docker
      package:
        name: docker-ce
        state: latest

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: upgrade pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: install docker-compose using pip
      pip:
        name: docker-compose
        executable: pip3

    - name: create docker usergroup
      group:
        name: docker
        state: present

    - name: Add admin user to docker group
      user:
        name: "{{ ansible_user }}"
        group: docker

    - name: create projects/netbox directory
      file:
        path: projects/netbox
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: docker

    - name: git checkout netbox
      git:
        repo: https://github.com/netbox-community/netbox-docker.git
        version: release
        dest: projects/netbox
        force: yes

    - name: copy docker-compose.override.yml over
      copy:
        src: ./docker-compose.override.yml
        dest: projects/netbox/docker-compose.override.yml
        owner: "{{ ansible_user }}"
        group: docker

    - name: pull netbox image from hub.docker.com
      community.general.docker_image:
        name: netboxcommunity/netbox:latest
        source: pull

    - name: edit netbox.env file, add napalm username
      lineinfile:
         path: projects/netbox/env/netbox.env
         regexp: '^NAPALM_USERNAME='
         line: 'NAPALM_USERNAME=cisco'
         owner: root

    - name: edit netbox.env file, add napalm password
      lineinfile:
         path: projects/netbox/env/netbox.env
         regexp: '^NAPALM_PASSWORD='
         line: 'NAPALM_PASSWORD=cisco'
         owner: root

    - name: start netbox container
      vars:
        ansible_python_interpreter: /usr/bin/python3
      community.general.docker_compose:
        project_src: ./projects/netbox
        state: present
  tags: netbox

# setup ansible AWX
- hosts: data_controller
  gather_facts: False
  become: yes
  tasks:
    - name: create projects/awx directory
      file:
        path: projects/awx
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: docker

    - name: git checkout awx
      git:
        repo: https://github.com/ansible/awx.git
        dest: projects/awx
        update: no

    - name: edit awx installer file - change http port number
      lineinfile:
         path: projects/awx/installer/inventory
         regexp: '^host_port=80'
         line: 'host_port=9000'
         owner: root

    - name: install ansible
      pip:
        name: ansible
        executable: pip3

    - name: install libselinux-python3
      yum:
        name: libselinux-python3
        state: latest

    - name: run awx install playbook
      shell:
        cmd: "ansible-playbook install.yml -i inventory"
        chdir: "projects/awx/installer"
      environment:
        PATH: '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/"{{ ansible_user }}"/.local/bin:/home/"{{ ansible_user }}"/bin'
  tags: awx
