---
# to execute: ansible-playbook playbook.yml -i hosts.yml -u <username> -K
- hosts: data_controller
  gather_facts: False
  become: yes
  tasks:
    - name: dnf update
      dnf:
        name: '*'
        state: latest
      register: dnf_output
